version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "interSQL101"
    ports:
      - "1433:1433"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        pid=\$!;
        sleep 20;
        echo '>>> Executando init.sql';
        /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'interSQL101' -C -i /docker-entrypoint-initdb.d/init.sql || true;
        wait \$pid
      "
